# Advanced server configuration
server:
  host: "0.0.0.0"
  port: 8000
  reload: true
  log_level: "info"
  cors_origins: ["*"]
  
providers:
  openai:
    priority: 1
    rate_limit: 60
    timeout: 30
    enabled: true
    models:
      - "gpt-4"
      - "gpt-4-turbo"
      - "gpt-3.5-turbo"
      - "gpt-3.5-turbo-16k"
  
  anthropic:
    priority: 2
    rate_limit: 50
    timeout: 30
    enabled: true
    models:
      - "claude-3-opus-20240229"
      - "claude-3-sonnet-20240229"
      - "claude-3-haiku-20240307"
  
  google:
    priority: 3
    rate_limit: 60
    timeout: 30
    enabled: true
    models:
      - "gemini-pro"
      - "gemini-pro-vision"

g4f:
  enabled: true
  retry_attempts: 3
  timeout: 30
  providers:
    - "Bing"
    - "ChatgptX"
    - "GPTalk"
    - "Liaobots"
    - "Phind"
    - "Yqcloud"
